'use client'
import Image from "next/image";
import { ReactHTMLElement, useRef } from "react";

const Home = () => {
  return (
      <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam malesuada eleifend interdum. Quisque a mauris a tellus blandit interdum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer lobortis at nibh vel finibus. Sed nibh neque, viverra id lorem ac, posuere lacinia nisi. Donec at porta libero. Aliquam semper pharetra est sit amet tincidunt. Curabitur sed metus tempus, tempus nisl et, congue metus. Vestibulum auctor libero lectus, a commodo tortor elementum eu. Maecenas tincidunt feugiat purus id euismod. Morbi quis aliquam massa. Quisque congue dolor ut velit eleifend auctor.

      Maecenas ut egestas erat. Proin et varius libero. Cras porta orci vel rutrum mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam rhoncus nulla nisl, non maximus quam venenatis efficitur. Curabitur ornare nulla vitae leo vulputate dictum. Praesent vitae mauris interdum, laoreet nibh vel, lacinia turpis. Morbi id libero sed sem interdum placerat. Donec lacinia tempor velit, in lacinia lacus posuere sit amet. Ut dapibus dignissim eros. Phasellus tristique, felis ac accumsan viverra, diam massa lacinia eros, et mattis elit est eget diam. Curabitur ultricies sem leo. Mauris luctus pretium tortor, a vulputate magna volutpat vitae. Cras pretium bibendum finibus.
      
      Sed sit amet nisl ut ante sagittis ullamcorper vel sed nisl. Fusce in elit id magna pharetra accumsan a vel nibh. Phasellus in tincidunt odio. Nam at aliquam nisl, ac eleifend arcu. Integer volutpat, eros nec mollis sodales, odio lorem aliquet dui, sed lobortis orci lacus eu orci. Maecenas sapien nisi, feugiat vel erat sed, cursus efficitur justo. Ut vulputate elementum mollis. Vestibulum volutpat sodales mi ut maximus. Donec mattis nisl eu dolor lacinia, tincidunt gravida augue malesuada. Nullam eu sollicitudin lectus, dictum ultricies mi. Nunc sed pellentesque tellus, id tincidunt orci.
      
      Nullam eget tincidunt lorem. Aenean tristique, turpis pellentesque iaculis fringilla, massa mi scelerisque est, eu efficitur mi nisl quis lectus. Morbi varius diam at malesuada faucibus. Aliquam ex purus, posuere ut justo in, elementum faucibus mauris. Donec in nibh nec mauris sagittis mattis. Vestibulum consectetur pretium urna, nec porta tellus tempor ut. In bibendum, dolor dictum sodales vehicula, mi nibh porttitor ipsum, pellentesque mattis tellus nisi et nisl. Mauris est mauris, pellentesque sed augue a, eleifend mollis tellus. Ut at nulla rutrum justo maximus placerat at id libero. Nullam ultricies metus sed metus porttitor, quis finibus augue malesuada. Fusce venenatis et tortor ut bibendum. Vestibulum dictum, leo vel vehicula vulputate, felis arcu mattis nisl, ac rhoncus massa metus et magna. Maecenas sed fermentum diam.</div>
  );
}
export default Home;